### ISSUE TITLE
Support Custom Merge Conflict Handling

### ISSUE THREAD

**Issue by Blacktiger** [ajoberstar/grgit#110]
If I try a merge with a merge conflict it throws an exception (per the documentation), however git status doesn't show the un-merged file as an uncommited or unstaged change because the change is technically an un-merged change.

In my case I have a situation that occurs fairly regularly where the only conflict is a change to the version of my artifact. During the merge I'd like to detect that as being the only conflict and handle the conflict automatically. I can almost do this with grgit (I just have to fix that change in the file), however the grgit.status() command doesn't report unmerged files. If it did, I could verify that only unmerged change was the version.

Alternatively, if there was an easy way to provide my own merge-conflict strategy through the jgit api I could just use a merge strategy to handle the merge conflict.

```
Repository folder:
    /var/folders/__/62r97n052blcnsrl5m82yt9998rb14/T/repository755216646387954970folder

Contents of modified file:
    <<<<<<< HEAD
    version=1.1.0-SNAPSHOT
    =======
    version=1.0.0
    >>>>>>> bc492414fbf153f7485e3e6efb0a7d281e51b50c

Output of grgit.status():
    org.ajoberstar.grgit.Status(staged:org.ajoberstar.grgit.Status$Changes(added:[], modified:[], removed:[]), unstaged:org.ajoberstar.grgit.Status$Changes(added:[], modified:[], removed:[]))

View from the command-line:
$ cd /var/folders/__/62r97n052blcnsrl5m82yt9998rb14/T/repository755216646387954970folder
$ git status
On branch develop
You have unmerged paths.
  (fix conflicts and run "git commit")

Unmerged paths:
  (use "git add <file>..." to mark resolution)

    both modified:   gradle.properties

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by Blacktiger** [comment]
For now I may work around the issue by using the jgit internals or by doing something like this hacky code:

```
try {
	grgit.merge(head: 'master', mode: Mode.CREATE_COMMIT)
} catch (Exception e) {
	println 'Conflicts Found:'
	new File(repositoryFolder).eachFileRecurse(FileType.FILES) { file ->
		if (file.text.contains('<<<<<<<')) {
			println "	$file"
		}
	}
}
```

**Comment by ajoberstar** [comment]
Now that I've dug into this a little bit, it looks like I neglected to include conflicting files in the `status` operation, which incorrectly implies that a repository is in a clean state after a failed merge. If this was added, I think it would give you what you need and expose a "bug" (at least a difference from the documented behavior). The Javadoc (and tests) indicate that a failed merge should abort the merge, putting the state back as it was, but the incomplete status hid this.

I definitely think that `Status` and `StatusOp` should be updated to include conflicting paths (for now I'd prefer to not to include more detail than just the paths).

The remaining decision is to do one of the following:

- Follow the documented behavior, which would mean that if the merge had a conflict, we throw a new exception type like in your PR, but it would include the status output rather than a JGit MergeResult, then we abort the changes (some type of resettting, etc to get back to clean state)
- Change the documented behavior to say that a failed merge will leave the conflicting files for the user to deal with. Update the existing exception message to indicate that you can call `grgit.status()` to identify the conflicting files. This approach would not provide any more information in the exception.

While I consider the current behavior a bug (based on what I expected it to be doing), the latter approach has the benefit of not breaking anyone who relies on the current behavior of letting the conflicting files stick around (and probably works better for your needs too). Let me know which approach you prefer, and if you're interested in submitting a revised PR. I'll plan to include this in the next release either way.

**Comment by Blacktiger** [comment]
Personally, I'd prefer to leave the files in the conflicted state so that
the user could handle the merge conflict they way they want to. That seems
like the simplest change and it still gives the user the ability to
investigate the merge conflicts. It's also more like the way fit handles
conflicts.

One other alternative would be to give the user the ability to specify a
closure to attempt to handle the conflict. If the closure returns true you
would assume it was handled correctly and that it as a merge success. If it
returned false you would abort the merge and throw an exception.

On Saturday, May 7, 2016, Andrew Oberstar <notifications@github.com> wrote:

> Now that I've dug into this a little bit, it looks like I neglected to
> include conflicting files in the status operation, which incorrectly
> implies that a repository is in a clean state after a failed merge. If this
> was added, I think it would give you what you need and expose a "bug" (at
> least a difference from the documented behavior). The Javadoc (and tests)
> indicate that a failed merge should abort the merge, putting the state back
> as it was, but the incomplete status hid this.
>
> I definitely think that Status and StatusOp should be updated to include
> conflicting paths (for now I'd prefer to not to include more detail than
> just the paths).
>
> The remaining decision is to do one of the following:
>
>    - Follow the documented behavior, which would mean that if the merge
>    had a conflict, we throw a new exception type like in your PR, but it would
>    include the status output rather than a JGit MergeResult, then we abort the
>    changes (some type of resettting, etc to get back to clean state)
>    - Change the documented behavior to say that a failed merge will leave
>    the conflicting files for the user to deal with. Update the existing
>    exception message to indicate that you can call grgit.status() to
>    identify the conflicting files. This approach would not provide any more
>    information in the exception.
>
> While I consider the current behavior a bug (based on what I expected it
> to be doing), the latter approach has the benefit of not breaking anyone
> who relies on the current behavior of letting the conflicting files stick
> around (and probably works better for your needs too). Let me know which
> approach you prefer, and if you're interested in submitting a revised PR.
> I'll plan to include this in the next release either way.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ajoberstar/grgit/issues/110#issuecomment-217640489>
>


-- 
Concentrate on the solution, not the problem.

**Comment by ajoberstar** [comment]
Yeah, leaving them conflicted sounds like the way to go.
