### ISSUE TITLE
More consistent exceptions

### ISSUE THREAD

**Issue by Barteks2x** [ajoberstar/grgit#146]
Sometimes it's jgit `RepositoryNotFoundException`, sometimes it's `GrgitException` and now I discovered `IllegalArgumentException`. Any way to have single exception I can catch instead?

**Comment by ajoberstar** [comment]
At the moment, no, it will differ based on the situation.

Some of this is due to a couple changes in JGit, but more consistency in exceptions is warranted. I think I'd target this as a 2.0 improvement since it could be breaking to some people.

**Comment by ajoberstar** [comment]
Another note on this is that the "context", I add in some places actually covers up a more useful message in the cause exception. Might be better off just wrapping the exception and not providing my own message.

**Comment by ajoberstar** [comment]
I realize this is kind of the opposite of what you were looking for but, for 2.0 I've decided to stop having a GrgitException at all. In practice, this means JGit's exception types will bubble up, which are more informative anyway. This does make your situation worse though, since you could get any number of exception types. If you do have a situation where you need to catch everything, you'll need to go all the way to `catch Exception`.

**Comment by Barteks2x** [comment]
Which is close to what I've been already doing. Right now I'm catching `RuntimeException` and not `Exception`, because nothing in these seems to throw any checked exceptions (and this is one of the cases where checked exception would be nicer).

**Comment by ajoberstar** [comment]
Groovy doesn't distinguish between checked/unchecked, so it should work out the same.
