### ISSUE TITLE
Getting a warning dialog on grgit.clone

### ISSUE THREAD

**Issue by leejavier** [ajoberstar/grgit#192]
Looks like the message in the warning is actually coming from my companies git settings but it usually just prints to the terminal.  When I'm using grgit.clone it will send that message in a popup modal and demands a click before moving on.  Is there a way to suppress this popup when I use grgit.clone?

![warning](https://user-images.githubusercontent.com/7944421/30075825-f57bfa74-9244-11e7-8432-8fdd6d1f9ac0.png)

**Comment by ajoberstar** [comment]
All of the input support was based around authentication use, though it seems to get used broader than that by JGit. In the [authentication](http://ajoberstar.org/grgit/grgit-authentication.html) documentation, there's a system property you can set to disable all interactive prompts: `org.ajoberstar.grgit.auth.interactive.allow`. However, depending on the nature of the input, this might just cause JGit to fail because it hasn't received any input. 

Let me know how it goes if you try that. I'm not entirely sure what the other options will be if that doesn't work though.

**Comment by leejavier** [comment]
I added org.ajoberstar.grgit.auth.interactive.allow=false to my gradle.properties file and it hasn't changed anything.  Not sure how to proceed except to write what I need with command line within gradle.

**Comment by leejavier** [comment]
Looks like that did the trick. Thanks!
