### ISSUE TITLE
Host Authenticity

### ISSUE THREAD

**Issue by AyalCiobotaru** [ajoberstar/grgit#199]
Is there a way to disable the check for host authenticity?
Running from the command line, it doesn't prompt me to continue connecting because authenticity of the host can't be established however running from Gradle, I get the prompt.

**Comment by ajoberstar** [comment]
I think there's an issue somewhere where the correct know hosts isn't being used. But as a workaround, see the example in the [Customizing the JSch Session](http://ajoberstar.org/grgit/grgit-authentication.html) section.

**Comment by ajoberstar** [comment]
Closing due to lack of response. Feel free to reopen, if you want to continue discussing this.

**Comment by ocroquette** [comment]
I had the same problem from Gradle, as a workaround I disabled the strict host key checking:

// https://raw.githubusercontent.com/ajoberstar/grgit/6047d52185fd6f24beb9a712555eea74b5137a68/docs/content/grgit-authentication.ad
java.lang.System.setProperty("org.ajoberstar.grgit.auth.session.config.StrictHostKeyChecking", "no")

**Comment by ocroquette** [comment]
Hello Andrew, I actually plan to stick to the version 2 because I use SSH as a protocol, and the version 2 has an embedded SSH client. It looks like the version 3 requires an external program, doesn't it?

**Comment by ajoberstar** [comment]
Yes, the plan was to stop using JSch (the Java SSH implementation) due to some of the issues like this host authenticity one that have come up. It will leverage your system `ssh` or `plink`, which I expect most systems would have available. 

However, that's still up for debate, so if there are benefits or features you get from JSch that should be preferred I'd be interested in some feedback over at #252.
