### ISSUE TITLE
Create/checkout a new branch and push changes to that branch?

### ISSUE THREAD

**Issue by urisun** [ajoberstar/grgit#212]
I am trying to achieve the following requirement. Clone a remote repo. Create/checkout a dynamic branch say 'test$(some_number)' on it, make some changes and push only this branch to remote.

I tried following code and went through your documentation multiple times. Can you help me when i am doing wrong.

```
def grgit = Grgit.clone(dir: ..., uri: ... ,credentials: ...)
    grgit.checkout(branch:'refs/heads/test'+<some_rand_numb>,createBranch:true,startPoint:'master')
   
    //modify a file
    grgit.add(patterns: [fileName])
    grgit.commit(message: 'updating test version')
    grgit.push()
    grgit.close()
```

It always publishes to master, instead of the required branch. Also, how can i print log for this branch instead of master?

**Comment by ajoberstar** [comment]
I believe what's happening is that setting startPoint will often treat that as your tracking branch. Thus, when you push it pushes to master instead of a remote.

When you clone, master should already be checked out. When you call checkout to create the new branch, you can omit the start point, and it will use the current HEAD (master, in this case) without tracking it.

At that point the push may work, though depending on your your gitconfig it may need you to set your upstream. Alternatively, you can provide a refspec to push to explicitly say to and from which branch you want pushed.

**Comment by urisun** [comment]
Can i use checkout to change current branch to existing branch? The idea is to create or change to exiting branch using a single checkout command.

Also, can i clone a repo to checkout a branch instead of master?

**Comment by ajoberstar** [comment]
Sorry for the delay. Yes, both of those can work. Check the [reference docs](http://ajoberstar.org/grgit/grgit-reference.html) for checkout and clone for details.

**Comment by urisun** [comment]
Thanks, I went through the documents and couldn't get it.

Wrote following  small shell script and calling it from gradle to get the required branch.
git clone <url>
cd <reponame>
git fetch
git checkout <branch_name> 2>/dev/null || git checkout -b <branch_name>

Will be happy to change to gradle in future if i can achieve it through checkout and clone.
