### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by ziem** [ajoberstar/grgit#334]
Hello,
On May 1st Bintray and JCenter will no longer be available:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ajoberstar** [comment]
See the update at the top of the README; I've made an alternate repo location available for the past versions. I don't have any planned updates to the project, but if I do they'll be published somewhere besides Bintray (GitHub Packages, Jitpack, or Central). I'm not too fond of going through the hassle of Central again, so I'm not going to commit to anything at this point.

**Comment by aalmiray** [comment]
@ajoberstar I hope you reconsider publishing to Maven Central as the idea to registering a custom repository does not work for everyone. It's nit just for immediate consumers of grgit, but anyone else that happens to encounter grgit in their transitive dependencies. The recently released (& upgraded) https://github.com/gradle-nexus/publish-plugin takes care of most of the hassle to publish JARs/POMs to Maven Central.

If everything else fails, I can offer myself to maintain the project, migrate publication to Maven Central, til someone else decides to tackle the growing list of issues.

**Comment by davormaricdev** [comment]
Hello, I am not able to Sync my project once I've migrated from jcenter to the maven url you have provided

Error message:
```
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not find any matches for org.eclipse.jgit:org.eclipse.jgit:latest.release as no versions of org.eclipse.jgit:org.eclipse.jgit are available.
     Searched in the following locations:
       - https://ajoberstar.org/bintray-backup/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml
     Required by:
         unspecified:unspecified:unspecified > org.ajoberstar.grgit:grgit-gradle:4.1.0 > org.ajoberstar.grgit:grgit-core:4.1.0
```

gradle file
```
buildscript {
    repositories {
        maven {
            name = 'ajoberstar-backup'
            url = 'https://ajoberstar.org/bintray-backup/'
        }
    }

    dependencies {
        classpath "org.ajoberstar.grgit:grgit-gradle:4.1.0"
    }
}
```

**Comment by vbrandl** [comment]
I think you also need `mavenCentral()` in your `repositories` block

**Comment by davormaricdev** [comment]
yep, that works @vbrandl. Thanks

**Comment by TWiStErRob** [comment]
I support @aalmiray's comment. I think moving from one easily disappearing repo to another is not a good idea. Any transitive user of yours will have to add this custom repo. Happy to help fixing publishing issues or setting up the plugin if there's PR to kick it off, @aalmiray/@ajoberstar.

I went through Maven Central publishing recently, it took me a few hours, but also I was doing it for the first time, it was quite simple actually following the [official docs](https://central.sonatype.org/publish/) or [any third party guide](https://www.albertgao.xyz/2018/01/18/how-to-publish-artifact-to-maven-central-via-gradle/). https://github.com/TWiStErRob/net.twisterrob.gradle/pull/108 ([latest version](https://github.com/TWiStErRob/net.twisterrob.gradle/blob/master/buildSrc/src/main/kotlin/net/twisterrob/gradle/build/PublishingPlugin.kt) changed a bit since then)

**Comment by ajoberstar** [comment]
As of 4.1.1, Grgit is back on Maven Central
