### ISSUE TITLE
Warning about `grgit` usage in Kotlin DSL buid scripts

### ISSUE THREAD

**Issue by Vampire** [ajoberstar/grgit#361]
The readme should have a warning, or the implementation be adjusted.
Currently if there is a Git repository, there is a `grgit` accessor generated for the Kotlin DSL.
But if there is no Git repository, the accessor is not generated as it is only generated as you only add an extra property in that case.
So if you usually have a Git repository and use the accessor, and then export the project to an archive without the GIt repository, the build is broken in there, as the build script will not compile anymore due to the missing accessor.

To mitigate that, you need to use some ugly construct like
```kts
val grgit = if (extra.has("grgit")) null else the<Grgit>()
```

**Comment by ajoberstar** [comment]
The existing behavior was kind of a hack a few years back, because it really shouldn't have been a direct `project.grgit` property, but it was kept around that way for compatibility. The switch to using an extension to get around a different issue required the ext workaround to set it to null if the repo didn't exist.

My gut is that I'll want to work out a solution for #362 and then try to wean people off the `org.ajoberstar.grgit` approach over to the service plugin.
