### ISSUE TITLE
Grgit instance is null on Windows.

### ISSUE THREAD

**Issue by Angular-Angel** [ajoberstar/grgit#372]
So I'm using the grgit gradle plugin to download stuff for my [build script](https://gitlab.com/AngularAngel/omnicraft/-/blob/dev-index/build.gradle), right? And it works fine on Linux, for me and another person. But, when my friend runs it on Windows, he gets:

```* What went wrong:
Execution failed for task ':buildModuleDevilUtil'.
> Cannot invoke method open() on null object
```

Which I'm pretty sure corresponds to line 34, where I go: `def repo = grgit.open(dir: moduleDir)`.

[Error Log.txt](https://github.com/ajoberstar/grgit/files/9587094/Error.Log.txt)

**Comment by SmashMaster** [comment]
![System Info](https://user-images.githubusercontent.com/6981448/190727807-b0f650e3-a8e4-46a5-ab65-9d83a3593d8d.PNG)

**Comment by ajoberstar** [comment]
The `grgit` variable is an instance of `Grgit` for the git repo the current Gradle project is inside. It will be null if it can't find a git repo in the Gradle project dir or one of its parents. Perhaps the Windows user has a copy of the source, but not in a Git repo.

However, the broader issue is that `grgit.open()` isn't an intended way to open a repository. You should instead be using it as a static method: `Grgit.open()`. I assume you were mislead by [the documentation](https://ajoberstar.org/grgit/main/grgit-open.html) which provides the wrong example, so I'll fix that.

So the two changes would be:

- Add an import for `org.ajoberstar.grgit.Grgit`
- Change the call to use `Grgit.open()` instead of `grgit.open()`

**Comment by Angular-Angel** [comment]
Ah, nice! Okay, Grgit works for me now. Thank you!
