### ISSUE TITLE
Support for rm -r

### ISSUE THREAD

**Issue by kenzierocks** [ajoberstar/grgit#54]
Recursive deletion is important to mimic `add --all` as specified in #53, however it is also useful for re-applying a `.gitignore` file.

**Comment by ajoberstar** [comment]
JGit's [RmCommand](http://download.eclipse.org/jgit/site/3.7.0.201502260915-r/apidocs/org/eclipse/jgit/api/RmCommand.html) doesn't have a recursive option. Does this have a usecase that isn't met with `remove(patterns:['.'])` or are you thinking it would be used with `cached: true`?

Since `grgit` is intended to be a subset of JGit with a friendlier API, I don't plan on implementing features not supported by JGit.

**Comment by kenzierocks** [comment]
Re-applying the `.gitignore` is done with `cached: true`, although I'm not sure that's a big usecase. If #53 is solved this shouldn't be much of a problem.

**Comment by ajoberstar** [comment]
Seems like this falls in the same category as #53. If someone wants to file the bug with JGit, the option can be added in grgit once that's fixed.
