### ISSUE TITLE
allow opt-out of 'uncommitted' logic

### ISSUE THREAD

**Issue by paleozogt** [ajoberstar/grgit#62]
Because of #60 (which appears to be due to a JGit bug), we can't use release-opinion with projects that use submodules on some systems.  JGit sees the submodule as 'modified', so release-opinion adds 'uncommitted' stuff to the generated version number.

Is it possible to turn off this logic?  That is, have release-opinion skip checking the `git status` check and only use `git describe` to drive its version number generation.

**Comment by ajoberstar** [comment]
This a `gradle-git` rather than a `grgit` thing (not that the line super-clear), but you have full control over that. Generally, I would suggest using `release-base` if you want to use custom logic, but you can make it work in `release-opinion` if needed.

See [Strategies](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/Strategies.groovy#L309) for how the development strategy is configured to enable the uncommitted logic (the `SHOW_UNCOMMITTED`). [OpinionReleasePlugin](https://github.com/ajoberstar/gradle-git/blob/master/src/main/groovy/org/ajoberstar/gradle/git/release/opinion/OpinionReleasePlugin.groovy) in the `project.release` block shows how you could configure `release-base`.

**Comment by paleozogt** [comment]
Thanks for the pointer.  Very nicely configurable system.  :)
