### ISSUE TITLE
Issue when .git is a file containing GIT_DIR

### ISSUE THREAD

**Issue by facewindu** [ajoberstar/grgit#65]
I have the following git repo structure

GIT_REPO
 |----- .git FILE
 |----- sub-repo (eclipse proj)

.git is a file, containing the GIT_DIR variable, pointing to the real location of the .git directory

If I perform Grgit.open('path/to/GIT_REPO/.git'), it fails, sayung the .git is not a directory.

Couldn't Grgit allow the use of .git file instead of .git directory ?
(Note that i'm not sure how Jgit behaves on this)

**Comment by ajoberstar** [comment]
At least initially, I think I have the same response to both of your questions. Let me know if you have further thoughts.

It seems unlikely that it doesn't behave like JGit, since [OpenOp](https://github.com/ajoberstar/grgit/blob/master/src/main/groovy/org/ajoberstar/grgit/operation/OpenOp.groovy#L59) directly calls JGit's `Git.open`. Maybe there's some flavor of it that I missed, but I would expect it's a difference between JGit and regular Git.

**Comment by facewindu** [comment]
Same comment than for issue #64 as well for me :)
JGit's FileRepositoryBuilder may contain methods to locate the git repo from the GIT_DIR variable stored in the .git file

I find that the JGit 'Git.open' are too restrictive, and do not use the full capabilities offered by jgit

**Comment by ajoberstar** [comment]
Can you try 1.3.0-milestone.1 to see if that resolves your issue? (call `Grgit.open()` instead of `Grgit.open(dir: 'something')`).

**Comment by facewindu** [comment]
Works like a charm, thanks Andrew :)
